/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import com.sun.beans.editors.IntegerEditor;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Vetores.Vetor;
import Vetores.VetorRandom;

/**
 *
 * @author dudy
 */
public class FrmPrincipal extends javax.swing.JDialog
{

    public String caminho;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BtnSelecao = new javax.swing.JToggleButton();
        txtCaminho = new javax.swing.JTextField();
        rBubbleSort = new javax.swing.JRadioButton();
        rSelectionsort = new javax.swing.JRadioButton();
        rInsertonSort = new javax.swing.JRadioButton();
        BtnComparar = new javax.swing.JToggleButton();
        rRandonico = new javax.swing.JRadioButton();
        lblSelect = new javax.swing.JLabel();
        lblInset = new javax.swing.JLabel();
        lblBubble = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BtnSelecao.setText("Seleção");
        BtnSelecao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnSelecaoActionPerformed(evt);
            }
        });

        rBubbleSort.setText("bubbleSort");

        rSelectionsort.setText("selectionsort");

        rInsertonSort.setText("insertonsort");

        BtnComparar.setText("Comparar");
        BtnComparar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnCompararActionPerformed(evt);
            }
        });

        rRandonico.setText("Vetor Randonico");

        lblSelect.setText("Tempo de processamento");

        lblInset.setText("Tempo de processamento");

        lblBubble.setText("Tempo de processamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rSelectionsort)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblSelect)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rRandonico))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnSelecao)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rInsertonSort)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInset))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rBubbleSort)
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBubble)
                                            .addComponent(BtnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator1, jSeparator2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSelecao)
                            .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSelectionsort)
                            .addComponent(lblSelect)))
                    .addComponent(rRandonico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rInsertonSort)
                    .addComponent(lblInset))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBubble)
                    .addComponent(rBubbleSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(BtnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSelecaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnSelecaoActionPerformed
    {//GEN-HEADEREND:event_BtnSelecaoActionPerformed
        JFileChooser filechoose = new JFileChooser();
        FileNameExtensionFilter ff = new FileNameExtensionFilter("text", "txt");
        filechoose.setDialogTitle("Seleção de Arquivo");
        filechoose.setFileSelectionMode(JFileChooser.FILES_ONLY);
        filechoose.setFileFilter(ff);
        int retorno = filechoose.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION)
        {
            File file = filechoose.getSelectedFile();
            this.caminho = file.getPath();
            txtCaminho.setText(caminho);
        }
    }//GEN-LAST:event_BtnSelecaoActionPerformed

    private void BtnCompararActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCompararActionPerformed
    {//GEN-HEADEREND:event_BtnCompararActionPerformed
        tratamentodedados.Ordenacao Ordena = new tratamentodedados.Ordenacao();
        Vetor vetor = new Vetor();
        int[] vet = null;
        if (rRandonico.isSelected())
        {
            VetorRandom rand = new VetorRandom();
            vet = rand.CriarVetor();
        }
        else
        {
            vet = vetor.CriarVetor(this.caminho);
        }
        int[] vet1 = vet;
        int[] vet2 = vet;
        int[] vet3 = vet;

        if (rSelectionsort.isSelected())
        {
            Ordena.selectionsort(vet1);
            lblSelect.setText(Integer.toString((int) Ordena.temposelectionsort)
                    + " milesegundos");
        }
        if (rBubbleSort.isSelected())
        {
            Ordena.bubbleSort(vet2);
            lblBubble.setText(Integer.toString((int) Ordena.tempobubbleSort)
                    + " milesegundos");
        }
        if (rInsertonSort.isSelected())
        {
            Ordena.insertonsort(vet3);
            lblInset.setText(Long.toString(Ordena.temposelectionsort)
                    + " milesegundos");
        }

        if (rSelectionsort.isSelected() && rBubbleSort.isSelected())
        {
            if (Ordena.tempobubbleSort < Ordena.temposelectionsort)
            {
                JOptionPane.showMessageDialog(null, "bubbleSort "
                        + Ordena.tempobubbleSort + " milesegundos "
                        + "\n selectionsort " + Ordena.temposelectionsort + " milesegundos "
                        + "\n bubbleSort foi mais eficiente");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "bubbleSort "
                        + Ordena.tempobubbleSort + " milesegundos "
                        + "\n selectionsort " + Ordena.temposelectionsort + " milesegundos "
                        + "\n selectionsort foi mais eficiente");
            }
        }

        if (rSelectionsort.isSelected() && rInsertonSort.isSelected())
        {
            if (Ordena.tempoinsertonsort < Ordena.temposelectionsort)
            {
                JOptionPane.showMessageDialog(null, " insertonsort "
                        + Ordena.tempoinsertonsort + " milesegundos "
                        + "\n selectionsort " + Ordena.temposelectionsort + " milesegundos "
                        + "\n insertonsort foi mais eficiente");
            }
            else
            {
                JOptionPane.showMessageDialog(null, " insertonsort "
                        + Ordena.tempoinsertonsort + " milesegundos "
                        + "\n selectionsort " + Ordena.temposelectionsort + " milesegundos "
                        + "\n selectionsort foi mais eficiente");
            }
        }
        if (rInsertonSort.isSelected() && rBubbleSort.isSelected())
        {
            if (Ordena.tempobubbleSort < Ordena.tempoinsertonsort)
            {
                JOptionPane.showMessageDialog(null, "bubbleSort "
                        + Ordena.tempobubbleSort + " milesegundos "
                        + "\n insertonsort " + Ordena.tempoinsertonsort + " milesegundos "
                        + "\n bubbleSort foi mais eficiente");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "bubbleSort "
                        + Ordena.tempobubbleSort + " milesegundos "
                        + "\n insertonsort " + Ordena.tempoinsertonsort + " milesegundos "
                        + "\n insertonsort foi mais eficiente");
            }
        }
    }//GEN-LAST:event_BtnCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FrmPrincipal dialog = new FrmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnComparar;
    private javax.swing.JToggleButton BtnSelecao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBubble;
    private javax.swing.JLabel lblInset;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JRadioButton rBubbleSort;
    private javax.swing.JRadioButton rInsertonSort;
    private javax.swing.JRadioButton rRandonico;
    private javax.swing.JRadioButton rSelectionsort;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
